/* ═══════════════════════════════════════════════════
       DESTINATION DATA — with proper name-wise thumbnails
    ═══════════════════════════════════════════════════ */

      const DESTS = [
        // ── MOST VISITED FIRST (sorted by annual visitor count) ──
        {
          name: "Taj Mahal",
          loc: "Agra, Uttar Pradesh",
          cat: "Heritage",
          emoji: "🕌",
          rating: 4.9,
          price: "₹1,100",
          season: "Oct–Mar",
          badge: "UNESCO",
          bg: "linear-gradient(145deg,#1a1228,#2a1a3a)",
          img: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
          desc: "One of the Seven Wonders of the World, an ivory-white marble mausoleum built by Mughal Emperor Shah Jahan. A timeless symbol of love and architectural perfection.",
          highlights: [
            "Sunrise View",
            "Mughal Gardens",
            "Mosque & Guest House",
            "Mehtab Bagh",
            "Light Show",
          ],
          tips: "Visit at sunrise for best photos. Entry free on Fridays. Carry water and sunscreen.",
        },
        {
          name: "Golden Temple",
          loc: "Amritsar, Punjab",
          cat: "Spiritual",
          emoji: "⭐",
          rating: 4.9,
          price: "₹1,000/day",
          season: "Oct–Mar",
          badge: "ICONIC",
          bg: "linear-gradient(145deg,#1a1208,#3a2a08)",
          img: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=600&q=80",
          desc: "The holiest Gurdwara gleaming in gold and marble, reflected in the sacred Sarovar. The Langar feeds 100,000+ people for free daily.",
          highlights: [
            "Golden Temple Visit",
            "Langar (Free Kitchen)",
            "Wagah Border Ceremony",
            "Jallianwala Bagh",
            "Amritsari Kulcha",
          ],
          tips: "Early morning or late evening for fewer crowds. Cover head and remove shoes. Wagah Border closes at sunset.",
        },
        {
          name: "Varanasi Ghats",
          loc: "Uttar Pradesh",
          cat: "Spiritual",
          emoji: "🪔",
          rating: 4.6,
          price: "₹2,000/day",
          season: "Oct–Mar",
          badge: "SACRED",
          bg: "linear-gradient(145deg,#1a0a0a,#3a1a08)",
          img: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&q=80",
          desc: "The spiritual capital—one of the world's oldest continuously inhabited cities. Ghats along the Ganges and the evening Ganga Aarti create a moving experience.",
          highlights: [
            "Ganga Aarti",
            "Boat Ride at Sunrise",
            "Kashi Vishwanath Temple",
            "Sarnath Visit",
            "Street Food Walk",
          ],
          tips: "Sunrise boat ride is unmissable. Aarti at Dashashwamedh Ghat at sunset. Wear modest clothing.",
        },
        {
          name: "Tirupati",
          loc: "Andhra Pradesh",
          cat: "Spiritual",
          emoji: "🙏",
          rating: 4.8,
          price: "₹1,500/day",
          season: "All Year",
          badge: "DIVINE",
          bg: "linear-gradient(145deg,#1a1208,#3a2210)",
          img: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80",
          desc: "Sri Venkateswara Temple atop seven hills—the most visited religious site in the world with 50,000+ daily pilgrims. Pure divine energy.",
          highlights: [
            "Tirumala Darshan",
            "Talakona Waterfalls",
            "Sri Padmavathi Temple",
            "Akasaganga Teertham",
            "TTD Laddu",
          ],
          tips: "Book darshan online weeks ahead. ₹300 special entry saves 8+ hrs. Carry minimal belongings.",
        },
        {
          name: "Red Fort",
          loc: "Delhi",
          cat: "Heritage",
          emoji: "🏯",
          rating: 4.5,
          price: "₹35",
          season: "Oct–Mar",
          badge: "ICONIC",
          bg: "linear-gradient(145deg,#2a0808,#4a1010)",
          img: "https://images.unsplash.com/photo-1585506942812-e72b29cef752?w=600&q=80",
          desc: "The magnificent Red Fort—residence of Mughal emperors for 200 years. Where India's PM hoists the national flag on Independence Day.",
          highlights: [
            "Diwan-i-Am",
            "Diwan-i-Khas",
            "Rang Mahal",
            "Moti Masjid",
            "Light Show",
          ],
          tips: "Evening light show is a must. Combine with Chandni Chowk food walk.",
        },
        {
          name: "Qutub Minar",
          loc: "Delhi",
          cat: "Heritage",
          emoji: "🕍",
          rating: 4.6,
          price: "₹300",
          season: "Nov–Mar",
          badge: "UNESCO",
          bg: "linear-gradient(145deg,#1a1a1a,#2a2210)",
          img: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&q=80",
          desc: "The tallest brick minaret in the world at 72.5 meters. A stunning Indo-Islamic architecture masterpiece dating back to 1193 AD.",
          highlights: [
            "Iron Pillar",
            "Alai Darwaza",
            "Quwwat-ul-Islam Mosque",
            "Garden Complex",
            "Iltutmish Tomb",
          ],
          tips: "Visit during golden hour. Audio guides available. Combine with Mehrauli Archaeological Park.",
        },
        {
          name: "Kedarnath",
          loc: "Uttarakhand",
          cat: "Spiritual",
          emoji: "⛰️",
          rating: 4.9,
          price: "₹3,500/day",
          season: "May–Nov",
          badge: "DIVINE",
          bg: "linear-gradient(145deg,#0a1220,#1a2230)",
          img: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
          desc: "At 3,583m among snow-capped Himalayas—one of the twelve Jyotirlingas. The 16 km trek is itself a spiritual journey through stunning mountains.",
          highlights: [
            "Kedarnath Temple",
            "16km Trek",
            "Chorabari Glacier",
            "Bhairavnath Temple",
            "Helicopter Darshan",
          ],
          tips: "Trek or helicopter (book well in advance). Season May–Nov only. Carry warm clothes even in summer.",
        },
        {
          name: "Amer Fort",
          loc: "Jaipur, Rajasthan",
          cat: "Heritage",
          emoji: "🏰",
          rating: 4.8,
          price: "₹550",
          season: "Oct–Feb",
          badge: "ICONIC",
          bg: "linear-gradient(145deg,#2a1a08,#4a2a10)",
          img: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
          desc: "Perched on a hilltop overlooking Maota Lake, a stunning blend of Hindu and Mughal architecture with the legendary Sheesh Mahal (Mirror Palace).",
          highlights: [
            "Sheesh Mahal",
            "Light & Sound Show",
            "Ganesh Pol Gate",
            "Maota Lake",
            "Elephant Rides",
          ],
          tips: "Book the light show in advance. Visit early morning for cooler weather.",
        },
        {
          name: "Calangute Beach",
          loc: "North Goa",
          cat: "Beaches",
          emoji: "🏖️",
          rating: 4.7,
          price: "₹3,500/day",
          season: "Nov–Feb",
          badge: "POPULAR",
          bg: "linear-gradient(145deg,#0c3d6e,#1565a8)",
          img: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80",
          desc: 'The "Queen of Beaches"—Goa\'s largest and most popular beach with water sports, beach shacks, and buzzing nightlife.',
          highlights: [
            "Water Sports",
            "Beach Shacks",
            "Saturday Night Market",
            "Fort Aguada",
            "Sunset Views",
          ],
          tips: "Weekdays for fewer crowds. Book water sports through hotel for better rates.",
        },
        {
          name: "Rishikesh",
          loc: "Uttarakhand",
          cat: "Spiritual",
          emoji: "🧘",
          rating: 4.8,
          price: "₹2,200/day",
          season: "Sep–Jun",
          badge: "YOGA CAPITAL",
          bg: "linear-gradient(145deg,#0a1e1a,#1a3e2a)",
          img: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&q=80",
          desc: "The Yoga Capital of the World on the holy Ganges amidst Himalayan foothills. Yoga ashrams to white-water rafting—spirituality meets adventure.",
          highlights: [
            "Yoga Ashrams",
            "White Water Rafting",
            "Beatles Ashram",
            "Laxman Jhula",
            "Triveni Ghat Aarti",
          ],
          tips: "Week-long yoga course for real transformation. Bungee jumping at Mohanchatti. Vegan food everywhere.",
        },
        {
          name: "Udaipur",
          loc: "Rajasthan",
          cat: "Urban",
          emoji: "🏰",
          rating: 4.8,
          price: "₹4,000/day",
          season: "Oct–Mar",
          badge: "LAKE CITY",
          bg: "linear-gradient(145deg,#0a1830,#1a2848)",
          img: "assets/images/udaipur_lake.png",
          desc: "India's most romantic city—City Palace, serene Lake Pichola, and the floating Taj Lake Palace create a fairy tale setting.",
          highlights: [
            "City Palace",
            "Lake Pichola Boat",
            "Jag Mandir Island",
            "Saheliyon ki Bari",
            "Monsoon Palace",
          ],
          tips: "Sunset from Ambrai Ghat. Boat to Jag Mandir for dinner. City Palace needs 3+ hours.",
        },
        {
          name: "Mumbai",
          loc: "Maharashtra",
          cat: "Urban",
          emoji: "🌆",
          rating: 4.5,
          price: "₹4,800/day",
          season: "Oct–Mar",
          badge: "MAX CITY",
          bg: "linear-gradient(145deg,#1a0a2e,#3a1550)",
          img: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&q=80",
          desc: "The city of dreams—Bollywood, colonial heritage, street-food culture. From Gateway of India to local trains, Mumbai pulses with unique energy.",
          highlights: [
            "Gateway of India",
            "Marine Drive Sunset",
            "Dharavi Tour",
            "Street Food Trail",
            "Leopold Cafe",
          ],
          tips: "Local train during off-peak for real Mumbai. Marine Drive sunset is unmissable. Try vada pav at Ashok.",
        },
        {
          name: "Old Delhi",
          loc: "Delhi",
          cat: "Urban",
          emoji: "🕌",
          rating: 4.6,
          price: "₹2,500/day",
          season: "Oct–Mar",
          badge: "CHAOTIC BEAUTY",
          bg: "linear-gradient(145deg,#1a1010,#2a1a18)",
          img: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&q=80",
          desc: "Labyrinthine lanes bursting with spices, street food, Mughal architecture, and organized chaos of 400 years of history.",
          highlights: [
            "Chandni Chowk Walk",
            "Jama Masjid",
            "Paranthe Wali Gali",
            "Spice Market",
            "Rickshaw Ride",
          ],
          tips: "Start at Jama Masjid, walk to Red Fort. Try parathas at Paranthe Wali Gali. Foot or cycle rickshaw.",
        },
        {
          name: "Mysore",
          loc: "Karnataka",
          cat: "Urban",
          emoji: "👑",
          rating: 4.7,
          price: "₹2,600/day",
          season: "Oct–Mar",
          badge: "PALACE CITY",
          bg: "linear-gradient(145deg,#1a1008,#2a2010)",
          img: "assets/images/mysuru_palace.png",
          desc: "The City of Palaces—regal heritage, silk sarees, sandalwood, and the Dasara festival. The illuminated Palace is one of India's most visited monuments.",
          highlights: [
            "Mysore Palace",
            "Chamundi Hills",
            "Brindavan Gardens",
            "Devaraja Market",
            "Silk Shopping",
          ],
          tips: "Sunday evenings—97,000 bulbs light the palace. Dasara in October is unforgettable. Buy silk from Cauvery Emporium.",
        },
        {
          name: "Hampi Ruins",
          loc: "Karnataka",
          cat: "Heritage",
          emoji: "🗿",
          rating: 4.8,
          price: "₹500",
          season: "Oct–Mar",
          badge: "UNESCO",
          bg: "linear-gradient(145deg,#2a1a08,#3a2010)",
          img: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&q=80",
          desc: "Ruins of the Vijayanagara Empire scattered across a surreal boulder-strewn landscape. Once richer than Rome, now a UNESCO heritage marvel.",
          highlights: [
            "Virupaksha Temple",
            "Stone Chariot",
            "Vittala Temple",
            "Matanga Hill Sunset",
            "Royal Enclosure",
          ],
          tips: "Rent a bicycle to explore. Stay on Hippie Island for budget. Best over 2–3 days.",
        },
        {
          name: "Ajanta Caves",
          loc: "Aurangabad, Maharashtra",
          cat: "Heritage",
          emoji: "🏙️",
          rating: 4.8,
          price: "₹250",
          season: "Nov–Mar",
          badge: "UNESCO",
          bg: "linear-gradient(145deg,#1a1208,#2a1c10)",
          img: "https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80",
          desc: "30 rock-cut Buddhist cave monuments from 2nd century BCE featuring extraordinary paintings—the finest surviving examples of ancient Indian art.",
          highlights: [
            "Cave 1 Paintings",
            "Cave 26 Buddha",
            "Waterfall View",
            "Ancient Murals",
            "Buddhist Viharas",
          ],
          tips: "Hire a guide. Caves closed Mondays. Comfortable walking shoes essential.",
        },
        {
          name: "Ellora Caves",
          loc: "Aurangabad, Maharashtra",
          cat: "Heritage",
          emoji: "⛩️",
          rating: 4.8,
          price: "₹250",
          season: "Nov–Mar",
          badge: "UNESCO",
          bg: "linear-gradient(145deg,#181220,#281a30)",
          img: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=600&q=80",
          desc: "34 caves representing Buddhist, Hindu, and Jain traditions. Kailasa Temple (Cave 16) is the largest monolithic rock excavation in the world.",
          highlights: [
            "Kailasa Temple",
            "Buddhist Caves",
            "Jain Caves",
            "Rock-cut Art",
            "Cave Sculptures",
          ],
          tips: "Plan half a day minimum. Photography allowed. Best with a knowledgeable guide.",
        },
        {
          name: "Konark Temple",
          loc: "Puri, Odisha",
          cat: "Heritage",
          emoji: "🌅",
          rating: 4.7,
          price: "₹40",
          season: "Oct–Mar",
          badge: "UNESCO",
          bg: "linear-gradient(145deg,#201808,#3a2810)",
          img: "https://images.unsplash.com/photo-1558618047-3bcd21db5a0f?w=600&q=80",
          desc: "A giant chariot with 24 intricately carved wheels and seven horses. An architectural masterpiece dedicated to the Hindu Sun God, Surya.",
          highlights: [
            "Stone Chariot Wheels",
            "Dance Hall",
            "Horse Sculptures",
            "Museum",
            "Chandrabhaga Beach",
          ],
          tips: "Attend Konark Dance Festival in December. Temple magical at sunrise. Combine with Puri.",
        },
        {
          name: "Alleppey",
          loc: "Kerala",
          cat: "Backwaters",
          emoji: "🛥️",
          rating: 4.8,
          price: "₹8,500/2nights",
          season: "Sep–Feb",
          badge: "BACKWATERS",
          bg: "linear-gradient(145deg,#0a2e1e,#145a38)",
          img: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
          desc: "Venice of the East—palm-fringed canals explored on traditional Kettuvallam houseboats. Wake to misty mornings and sleep to gentle rocking.",
          highlights: [
            "Houseboat Stay",
            "Backwater Cruise",
            "Village Cycling",
            "Toddy Shop Lunch",
            "Mararikulam Beach",
          ],
          tips: "Premium houseboat with AC and upper deck. Avoid weekends. Sunset from upper deck is magical.",
        },
        {
          name: "Jodhpur",
          loc: "Rajasthan",
          cat: "Urban",
          emoji: "🔵",
          rating: 4.7,
          price: "₹3,200/day",
          season: "Oct–Feb",
          badge: "BLUE CITY",
          bg: "linear-gradient(145deg,#0a1040,#1a2060)",
          img: "https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80",
          desc: "The Blue City—indigo-washed houses surrounding Mehrangarh Fort. One of India's most photogenic cities blending royal history and street life.",
          highlights: [
            "Mehrangarh Fort",
            "Blue City Walk",
            "Clock Tower Market",
            "Umaid Bhawan Palace",
            "Zip-lining",
          ],
          tips: "Blue city walking tour at sunrise is magical. Try mirchi vada. Zip-line from Mehrangarh Fort.",
        },
        {
          name: "Kolkata",
          loc: "West Bengal",
          cat: "Urban",
          emoji: "🎨",
          rating: 4.6,
          price: "₹2,800/day",
          season: "Oct–Mar",
          badge: "CITY OF JOY",
          bg: "linear-gradient(145deg,#1a1028,#2a1a38)",
          img: "https://images.unsplash.com/photo-1558431382-27e303142255?w=600&q=80",
          desc: "The cultural capital—literary festivals, art galleries, Durga Puja pandals, and the best street food in the country. The iconic Howrah Bridge spans the Hooghly River.",
          highlights: [
            "Victoria Memorial",
            "Howrah Bridge",
            "Kumartuli Idol Makers",
            "Park Street",
            "Durga Puja",
          ],
          tips: "Visit during Durga Puja (Oct) for the most spectacular festival. Try phuchka. Hand-pulled rickshaw in North Kolkata.",
        },
        {
          name: "Ranthambhore",
          loc: "Rajasthan",
          cat: "Wildlife",
          emoji: "🐅",
          rating: 4.8,
          price: "₹8,000/day",
          season: "Oct–Jun",
          badge: "TIGER RESERVE",
          bg: "linear-gradient(145deg,#1a1008,#2a2010)",
          img: "https://images.unsplash.com/photo-1549366021-9f761d450615?w=600&q=80",
          desc: "One of India's best places to spot wild Bengal tigers. Ancient fort overlooks the park where tigers roam among historic ruins and lakes.",
          highlights: [
            "Tiger Safari",
            "Ranthambhore Fort",
            "Padam Talao Lake",
            "Crocodile Spotting",
            "Birdwatching",
          ],
          tips: "Book zone 1–5 for best sightings. Carry binoculars and telephoto lens. Morning safaris best.",
        },
        {
          name: "Jim Corbett",
          loc: "Nainital, Uttarakhand",
          cat: "Wildlife",
          emoji: "🦁",
          rating: 4.7,
          price: "₹7,500/day",
          season: "Nov–Jun",
          badge: "TIGER RESERVE",
          bg: "linear-gradient(145deg,#0a1e08,#1a3e10)",
          img: "https://images.unsplash.com/photo-1615824996195-f780bba7cfab?w=600&q=80",
          desc: "India's oldest national park (1936). Named after hunter-turned-conservationist Jim Corbett. Home to 200+ tigers, elephants, leopards, 600+ bird species.",
          highlights: [
            "Dhikala Zone Safari",
            "Bijrani Zone",
            "Jhirna Gate",
            "Elephant Safari",
            "Corbett Museum",
          ],
          tips: "Dhikala zone is best but needs overnight booking. Book permits months ahead. Avoid monsoon.",
        },
        {
          name: "Kaziranga",
          loc: "Assam",
          cat: "Wildlife",
          emoji: "🦏",
          rating: 4.9,
          price: "₹6,000/day",
          season: "Nov–Apr",
          badge: "UNESCO",
          bg: "linear-gradient(145deg,#0a2010,#1a4020)",
          img: "https://images.unsplash.com/photo-1504173010664-32509aeebb62?w=600&q=80",
          desc: "Home to two-thirds of the world's one-horned rhinoceros. Also shelters wild buffalo, swamp deer, elephants, and Bengal tigers.",
          highlights: [
            "Rhino Safari",
            "Elephant Ride",
            "Central Range",
            "Tea Garden Visit",
            "Birdwatching",
          ],
          tips: "Elephant safaris at dawn—book day before. Central and Western ranges best for rhinos.",
        },
        {
          name: "Radhanagar Beach",
          loc: "Andaman",
          cat: "Beaches",
          emoji: "🐠",
          rating: 4.9,
          price: "₹4,000/day",
          season: "Nov–Apr",
          badge: "TOP RATED",
          bg: "linear-gradient(145deg,#0a2a4a,#1a5a8a)",
          img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
          desc: "Consistently ranked among Asia's best—powdery white sand, turquoise waters, and pristine tropical forest backdrop.",
          highlights: [
            "Crystal Clear Water",
            "Snorkeling",
            "Sunset Point",
            "Elephant Beach",
            "Scuba Diving",
          ],
          tips: "Reach by 3pm for best sunset. No facilities after dark. Reef-safe sunscreen only.",
        },
        {
          name: "Spiti Valley",
          loc: "Himachal Pradesh",
          cat: "Mountains",
          emoji: "🏔️",
          rating: 4.9,
          price: "₹4,200/day",
          season: "Jun–Sep",
          badge: "REMOTE",
          bg: "linear-gradient(145deg,#1a2a4a,#243859)",
          img: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
          desc: "A cold desert at 12,500 feet—stark landscapes, ancient monasteries, and starlit skies make it a dream for adventurers.",
          highlights: [
            "Key Monastery",
            "Chandratal Lake",
            "Dhankar Gompa",
            "Kibber Village",
            "Stargazing",
          ],
          tips: "Acclimatize before heading up. Carry altitude sickness meds. Roads open Jun–Oct only.",
        },
        {
          name: "Nubra Valley",
          loc: "Ladakh",
          cat: "Mountains",
          emoji: "🐪",
          rating: 4.9,
          price: "₹5,000/day",
          season: "Jun–Sep",
          badge: "HIGH ALT.",
          bg: "linear-gradient(145deg,#1a1830,#2a2840)",
          img: "https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=600&q=80",
          desc: "Double-humped Bactrian camels on sand dunes at 10,000 feet. The drive through Khardung La (one of the highest roads) is unforgettable.",
          highlights: [
            "Hunder Sand Dunes",
            "Diskit Monastery",
            "Bactrian Camel Safari",
            "Khardung La Pass",
            "Hot Springs",
          ],
          tips: "Carry cash—ATMs unreliable. Acclimatize in Leh first (2+ days). Permits required.",
        },
        {
          name: "Palolem Beach",
          loc: "South Goa",
          cat: "Beaches",
          emoji: "🛶",
          rating: 4.8,
          price: "₹3,200/day",
          season: "Nov–Feb",
          badge: "SERENE",
          bg: "linear-gradient(145deg,#0a3040,#1a6080)",
          img: "https://images.unsplash.com/photo-1468413253725-0d5181091126?w=600&q=80",
          desc: "A crescent-shaped bay fringed with coconut palms. South Goa's crown jewel—kayak to Butterfly Beach or spot dolphins at dawn.",
          highlights: [
            "Kayaking",
            "Dolphin Spotting",
            "Silent Noise Parties",
            "Beach Hut Stays",
            "Sunset Kayaking",
          ],
          tips: "Book beachfront huts early. Silent disco parties are legendary. Try the dolphin trip.",
        },
        {
          name: "Ajmer Sharif",
          loc: "Rajasthan",
          cat: "Spiritual",
          emoji: "🕌",
          rating: 4.6,
          price: "₹1,200/day",
          season: "Oct–Mar",
          badge: "SUFI",
          bg: "linear-gradient(145deg,#1a0808,#2a1010)",
          img: "https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80",
          desc: "The Ajmer Sharif Dargah shrine of Sufi saint Moinuddin Chishti attracts devotees from all faiths. Urs Festival features qawwali and prayers.",
          highlights: [
            "Dargah Sharif",
            "Ana Sagar Lake",
            "Adhai Din Ka Jhonpra",
            "Taragarh Fort",
            "Urs Festival",
          ],
          tips: "Early morning or evening for peaceful darshan. Respectful attire. Combine with Pushkar day trip.",
        },
        {
          name: "Rohtang Pass",
          loc: "Manali, HP",
          cat: "Mountains",
          emoji: "❄️",
          rating: 4.7,
          price: "₹3,500/day",
          season: "May–Oct",
          badge: "SCENIC",
          bg: "linear-gradient(145deg,#1a2848,#2a3868)",
          img: "https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=600&q=80",
          desc: "At 3,978 meters—a gateway between Kullu Valley and Lahaul-Spiti with snow-covered peaks, glaciers, and panoramic views.",
          highlights: [
            "Snow Activities",
            "Panoramic Views",
            "Beas Kund Trek",
            "Atal Tunnel",
            "Glacier Walk",
          ],
          tips: "Permits required—book online. Weather changes quickly; carry warm layers. Avoid weekends.",
        },
        {
          name: "Varkala Cliffs",
          loc: "Kerala",
          cat: "Beaches",
          emoji: "🪨",
          rating: 4.7,
          price: "₹2,500/day",
          season: "Oct–Mar",
          badge: "SCENIC",
          bg: "linear-gradient(145deg,#1a0c0a,#3a1a10)",
          img: "https://images.unsplash.com/photo-1476673160081-cf065607f449?w=600&q=80",
          desc: "Dramatic red laterite cliffs dropping into the Arabian Sea. The cliff-top path is lined with cafes offering breathtaking ocean views.",
          highlights: [
            "Cliff Walks",
            "Papanasam Beach",
            "Janardanaswamy Temple",
            "Ayurvedic Spas",
            "Cliff Cafes",
          ],
          tips: "Stay at cliff-edge properties for ocean views. Great Ayurvedic massage options nearby.",
        },
        {
          name: "Chopta Valley",
          loc: "Uttarakhand",
          cat: "Mountains",
          emoji: "🦌",
          rating: 4.8,
          price: "₹2,800/day",
          season: "Apr–Jun",
          badge: "MINI SWISS",
          bg: "linear-gradient(145deg,#0a1e1a,#1a3e2a)",
          img: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
          desc: '"Mini Switzerland of India"—a pristine meadow surrounded by forests of pine, deodar, and rhododendron. Base for Tungnath trek.',
          highlights: [
            "Tungnath Trek",
            "Chandrashila Summit",
            "Deoria Tal",
            "Rhododendron Forests",
            "Winter Snowfall",
          ],
          tips: "Tungnath trek moderate; doable in one day. Camp at Deoria Tal for stunning reflections.",
        },
        {
          name: "Coorg",
          loc: "Karnataka",
          cat: "Mountains",
          emoji: "☕",
          rating: 4.7,
          price: "₹3,800/day",
          season: "Oct–Mar",
          badge: "COFFEE LAND",
          bg: "linear-gradient(145deg,#0a1e0a,#1a3e1a)",
          img: "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=600&q=80",
          desc: '"Scotland of India"—Coorg is famous for coffee plantations, waterfalls, and the warm hospitality of the Kodava people.',
          highlights: [
            "Coffee Plantation Tour",
            "Abbey Falls",
            "Raja's Seat",
            "Namdroling Monastery",
            "Iruppu Falls",
          ],
          tips: "Stay at a homestay for authentic cuisine. Visit a coffee estate. Best explored by self-drive.",
        },
        {
          name: "Periyar",
          loc: "Kerala",
          cat: "Wildlife",
          emoji: "🐘",
          rating: 4.7,
          price: "₹4,500/day",
          season: "Oct–Mar",
          badge: "BIOSPHERE",
          bg: "linear-gradient(145deg,#0a1e18,#1a3e28)",
          img: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=600&q=80",
          desc: "Tiger and elephant reserve around an artificial lake in the cardamom hills. Unique boat safaris let you watch elephants bathing from the water.",
          highlights: [
            "Boat Safari",
            "Bamboo Rafting",
            "Spice Garden Tour",
            "Elephant Junction",
            "Night Patrol",
          ],
          tips: "Bamboo rafting is exceptional for photography. Visit a cardamom plantation. Ayurvedic massage after safari.",
        },
        {
          name: "Sundarbans",
          loc: "West Bengal",
          cat: "Wildlife",
          emoji: "🐊",
          rating: 4.6,
          price: "₹5,000/day",
          season: "Oct–Mar",
          badge: "UNESCO",
          bg: "linear-gradient(145deg,#081818,#183030)",
          img: "https://images.unsplash.com/photo-1440342359743-84fcb8c21f21?w=600&q=80",
          desc: "The world's largest mangrove forest, home to the Royal Bengal Tiger that swims through tidal waterways. A surreal world of water, mud, and green.",
          highlights: [
            "Tiger Tracking Boat Safari",
            "Mangrove Walks",
            "Sajnekhali Watch Tower",
            "Crocodile Spotting",
            "Honey Collectors",
          ],
          tips: "Multi-day boat excursions best for tiger spotting. Carry insect repellent. Gov-approved guides mandatory.",
        },
        {
          name: "Kumarakom",
          loc: "Kerala",
          cat: "Backwaters",
          emoji: "🐦",
          rating: 4.8,
          price: "₹9,000/2nights",
          season: "Oct–Feb",
          badge: "BIRD SANCTUARY",
          bg: "linear-gradient(145deg,#081e18,#143830)",
          img: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=600&q=80",
          desc: "On the banks of Vembanad Lake, famous for its bird sanctuary and luxury resorts. Migratory birds from Siberia visit Nov–Feb.",
          highlights: [
            "Bird Sanctuary",
            "Vembanad Lake Cruise",
            "Ayurvedic Resort",
            "Village Life Tour",
            "Fishing Experience",
          ],
          tips: "Visit 6 AM for bird sightings. Combine with Alleppey. Luxury resorts offer Ayurvedic packages.",
        },
        {
          name: "Kollam Backwaters",
          loc: "Kerala",
          cat: "Backwaters",
          emoji: "🌴",
          rating: 4.6,
          price: "₹7,000/2nights",
          season: "Oct–Feb",
          badge: "SERENE",
          bg: "linear-gradient(145deg,#0a2a1a,#1a4a2a)",
          img: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=600&q=80",
          desc: "Southern gateway to Kerala's backwaters with the longest stretch. Ashtamudi Lake cruise is less crowded and more authentic.",
          highlights: [
            "Ashtamudi Lake Cruise",
            "Cashew Factories",
            "Thirumullavaram Beach",
            "Palaruvi Waterfall",
            "Krishnapuram Palace",
          ],
          tips: "8-hour public ferry from Kollam to Alleppey for authentic experience. Try cashew feni.",
        },
        {
          name: "Marina Beach",
          loc: "Chennai, TN",
          cat: "Beaches",
          emoji: "🌊",
          rating: 4.4,
          price: "₹500/day",
          season: "Nov–Mar",
          badge: "LARGEST",
          bg: "linear-gradient(145deg,#0a1a3a,#1a3a6a)",
          img: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80",
          desc: "The second longest urban beach in the world at 13 km along the Bay of Bengal. A cultural hub with stalls, horse rides, and Madras vibes.",
          highlights: [
            "Evening Sundal Stalls",
            "Lighthouse",
            "Fort St George",
            "MGR Memorial",
            "Sunrise Walk",
          ],
          tips: "Visit evenings for street food. Don't swim—currents strong. Great sunrise photography.",
        },
        {
          name: "Gokarna Beach",
          loc: "Karnataka",
          cat: "Beaches",
          emoji: "🕉️",
          rating: 4.7,
          price: "₹1,800/day",
          season: "Oct–Mar",
          badge: "HIDDEN GEM",
          bg: "linear-gradient(145deg,#0a2a1a,#1a5a3a)",
          img: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80",
          desc: "Goa vibes minus commercialization. Trek between Om Beach, Half Moon, and Paradise Beach for unforgettable coastal scenery.",
          highlights: [
            "Om Beach",
            "Half Moon Beach Trek",
            "Mahabaleshwar Temple",
            "Paradise Beach",
            "Cliff Camping",
          ],
          tips: "Trek Om to Paradise Beach for magic. Carry water and snacks. Camp overnight at Half Moon.",
        },
        {
          name: "Ziro Valley",
          loc: "Arunachal Pradesh",
          cat: "Mountains",
          emoji: "🌾",
          rating: 4.8,
          price: "₹3,000/day",
          season: "Sep–Oct",
          badge: "UNESCO NOM.",
          bg: "linear-gradient(145deg,#0a1a0a,#1a3a1a)",
          img: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80",
          desc: "Home to the Apatani tribe—lush green valley with rice fields, bamboo groves, and pine-clad hills. The Ziro Music Festival is Gen Z legend.",
          highlights: [
            "Ziro Music Festival",
            "Apatani Villages",
            "Rice Terraces",
            "Tarin Fish Farm",
            "Talley Valley",
          ],
          tips: "Music fest in late September—book months ahead. Inner Line Permit required.",
        },
      ];

      
